# Override http_archive for local testing
local_repository(
    name = "com_fasterci_rules_mirror",
    path = "../..",
)

#---SNIP--- Below here is re-used in the workspace snippet published on releases

######################
# rules_mirror setup #
######################
# Fetches the rules_mirror dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
load("//mirror:repositories.bzl", "rules_mirror_dependencies")

rules_mirror_dependencies()
