# configure vscode yaml support https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# yaml-language-server: $schema=https://fasterci.com/config.schema.json
workflows:

  - &build_workflow
    name: Faster CI / build (current)
    image: us.gcr.io/fasterci/bazelbuilder:9530886
    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - "**"
    init: |
      kubectl config set-cluster kind --insecure-skip-tls-verify=true --server=http://127.0.0.1
    steps:
      - name: Build & test
        bazel:
          build_targets:
            - //...
          test_flags:
            - --test_size_filters=-large,-enormous
          test_targets:
            - //...

  - <<: *build_workflow
    name: Faster CI / build (6.3.1)
    env:
      USE_BAZEL_VERSION: "6.3.1"
